security:
    encoders:
        App\Application\Model\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Application\Model\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        authorization:
            pattern:  ^/api/auth
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: true

    access_control:
    - { path: ^/api/auth, roles: ROLE_GUEST }
    - { path: ^/api, roles: ROLE_USER }
